# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivado/vr_code/assembly_CPU/assembly_CPU.srcs/sources_1/ip/instructionROM_1/instructionROM.xci
# IP: The module: 'instructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/vr_code/assembly_CPU/assembly_CPU.srcs/sources_1/ip/instructionROM_1/instructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instructionROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/vivado/vr_code/assembly_CPU/assembly_CPU.srcs/sources_1/ip/instructionROM_1/instructionROM.xci
# IP: The module: 'instructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado/vr_code/assembly_CPU/assembly_CPU.srcs/sources_1/ip/instructionROM_1/instructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instructionROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
